name: AArch64 Linux Bazel

on:
  push:
  pull_request:
  schedule:
    # min hours day(month) month day(week)
    - cron: '0 0 7,22 * *'

jobs:
  # Building using the github runner environement directly.
  bazel:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Bazel through bazelisk
        run: |
          wget  https://github.com/bazelbuild/bazelisk/releases/download/v1.18.0/bazelisk-linux-arm64
          chmod +x bazelisk-linux-arm64
          ./bazelisk-linux-arm64 --version
      - name: Test
        run: ./bazelisk-linux-arm64 test -s --verbose_failures //...
