name: aarch64 Linux Zig

on: [push, pull_request]

permissions: read-all

jobs:
  run:
    strategy:
      matrix:
        target:
          - aarch64-linux-musl
          - aarch64-linux-gnu
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6
      - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29  # v2
        with:
          version: 0.16.0
      - name: Build
        run: zig build -Dtarget=${{ matrix.target }}
      - name: Run list_cpu_features
        run: ./zig-out/bin/list_cpu_features --json
