name: AArch64 Linux Bazel

on:
  push:
  pull_request:
  schedule:
    # min hours day(month) month day(week)
    - cron: '0 0 7,22 * *'

jobs:
  # Building using the GitHub runner environement directly.
  bazel:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Build
        run: make --directory=bazel/ci arm64_build
      - name: Test
        run: make --directory=bazel/ci arm64_test
