name: amd64 Linux Zig

on: [push, pull_request]

jobs:
  run:
    strategy:
      matrix:
        target:
          - x86_64-linux-musl
          - x86_64-linux-gnu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: mlugg/setup-zig@v2
        with:
          version: latest
      - name: Build
        run: zig build -Dtarget=${{ matrix.target }}
      - name: Run list_cpu_features
        run: ./zig-out/bin/list_cpu_features --json
