name: amd64 Linux Bazel

on:
  push:
  pull_request:
  schedule:
    # min hours day(month) month day(week)
    - cron: '0 0 7,22 * *'

permissions: read-all

jobs:
  # Building using the github runner environement directly.
  bazel:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6
      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3  # v4
      - name: Check docker
        run: |
          docker info
          docker buildx ls
      - name: Build
        run: make --directory=bazel/ci amd64_build
      - name: Test
        run: make --directory=bazel/ci amd64_test
