# ref: https://github.com/actions/runner-images
name: Arm64 Windows CMake

on:
  push:
  pull_request:
  schedule:
    # min hours day(month) month day(week)
    - cron: '0 0 7,22 * *'

jobs:
  # Building using the github runner environement directly.
  make:
    runs-on: windows-11-arm
    env:
      CTEST_OUTPUT_ON_FAILURE: 1
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -S. -Bbuild -G "Visual Studio 17 2022" -A ARM64 -DCMAKE_CONFIGURATION_TYPES=Release
      - name: Build
        run: cmake --build build --config Release --target ALL_BUILD -- /maxcpucount
      - name: Test
        run: cmake --build build --config Release --target RUN_TESTS -- /maxcpucount
      - name: Install
        run: cmake --build build --config Release --target INSTALL -- /maxcpucount