name: arm Linux

on:
  push:
  pull_request:
  schedule:
    # min hours day(month) month day(week)
    - cron: '0 0 7,22 * *'

jobs:
  # Building using the github runner environement directly.
  arm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets: [
          [arm-linux-gnueabihf],
          [armv8l-linux-gnueabihf],
          [arm-linux-gnueabi],
          [armeb-linux-gnueabihf],
          [armeb-linux-gnueabi]
        ]
      fail-fast: false
    env:
      TARGET: ${{ matrix.targets[0] }}
      CTEST_OUTPUT_ON_FAILURE: 1
    steps:
    - uses: actions/checkout@v2
    - name: Install Ninja
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build
    - name: Build
      run: ./scripts/run_integration.sh build
    - name: Test
      run: ./scripts/run_integration.sh test
