name: clang-format Check

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  clang-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build clang-format docker
      run: cd .github/workflows && docker build --tag=linter .

    - name: Check clang-format
      run: docker run --rm --init -v $(pwd):/repo linter:latest clang-format --version
    - name: clang-format help
      run: docker run --rm --init -v $(pwd):/repo linter:latest clang-format --help

    - name: Check include
      run: docker run --rm --init -v $(pwd):/repo linter:latest sh -c "find /repo/include \( -iname '*.c' -or -iname '*.h' -or -iname '*.cc' \) | xargs clang-format --style=file --Werror --dry-run"
    - name: Check src
      run: docker run --rm --init -v $(pwd):/repo linter:latest sh -c "find /repo/src \( -iname '*.c' -or -iname '*.h' -or -iname '*.cc' \) | xargs clang-format --style=file --Werror --dry-run"
    - name: Check test
      run: docker run --rm --init -v $(pwd):/repo linter:latest sh -c "find /repo/test \( -iname '*.c' -or -iname '*.h' -or -iname '*.cc' \) | xargs clang-format --style=file --Werror --dry-run"
